class InternalErrorException(Exception):
    def __init__(self, message, errors):
        pass
